### ISSUE TITLE
With version 3.2.0 Jupyter Notebook Not Launching

### ISSUE THREAD

**Issue by rohan-paul** [Julian/jsonschema#773]
When I have v 3.2.0 and trying to launch Jupyter Lab or Notebook its not launching and getting below errors.

But downgrading jsonschema to version 3.0.2 makes everything work again.

```
Traceback (most recent call last):
  File "C:\Users\srish\Anaconda3\lib\site-packages\jsonschema\__init__.py", line 31, in <module>
    from importlib import metadata
ImportError: cannot import name 'metadata' from 'importlib' (C:\Users\srish\Anaconda3\lib\importlib\__init__.py)

During handling of the above exception, another exception occurred:
```

Same happened with both Python 3.8 and 3.7

**Comment by Julian** [comment]
How did you install jsonschema?

Seems possible it was with an old version of pip.

jsonschema [declares its dependency on importlib-metadata for versions of Python that don't ship with it](https://github.com/Julian/jsonschema/blob/main/setup.cfg#L31).

Definitely would be suspicious if that didn't work on 3.8 though, where it's part of the standard library.

**Comment by Julian** [comment]
Closing, but happy to review if you provide some info here.
